---
- name: Staging server Deployment
  hosts: stageserver
  become_user: root
  become: true
  vars:
    repo_path: nrbaskar/react:{{ DOCKER_TAG }}
    dest_path: /home/ec2-user/{{ DOCKER_TAG }}

  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present

    - name: Install docker
      yum:
        name: docker
        state: present

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present

    - name: Pull docker image
      docker_image:
        name: "{{ repo_path }}"
        tag: "{{ DOCKER_TAG }}"
        source: pull

    - name: Create directory
      file:
        state: directory
        dest: "{{ dest_path }}"

    - name: Copy Files
      shell: 'aws s3 cp s3://react555-s3bucket/node_sonar_S3bucket.zip "{{ dest_path }}/node_sonar_S3bucket.zip"'

    - name: Unzip Files
      shell: 'unzip "{{ dest_path }}/node_sonar_S3bucket.zip"'

    - name: Install Nodejs & ExpressJS
      shell: 'curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -'

    - name: Install required packages
      yum:
        name: nodejs
        state: present

    - name: Install Expressjs
      command: sudo npm install express

    - name: Install React JS package
      command: npm install -g create-react-app

    - name: Install react-dependencies
      command: npm i react-scripts build
      args:
        chdir: "{{ dest_path }}/node_sonar_S3bucket"

    - name: Install all necessary Node modules
      command: npm install
      args:
        chdir: "{{ dest_path }}/node_sonar_S3bucket"

    - name: Install pm2
      npm:
        name: pm2
        global: yes
        state: present

    - name: Get pm2 status
      command: pm2 status
      register: pm2_status
      changed_when: false

    - name: Kill pm2 service
      command: pm2 kill

    - name: Start service
      command: pm2 start npm -- start ./server/app.js --name "{{ DOCKER_TAG }}-Service"
      args:
        chdir: "{{ dest_path }}/node_sonar_S3bucket"
