---
- name: Staging server Deployment
  hosts: stageserver
  become_user: root
  become: True
  vars:
   # repo_path: nrbaskar/nodejeapp:{{DOCKER_TAG}}
    dest_path: /home/devsecops/wilfred/{{DOCKER_TAG}}
  tasks:   
    #Create a Directory
    - name: create directory
      file:
        state: directory
        dest: "{{ dest_path }}"
    #Copy Files
    - name: Copy website to the host
      copy:
        src: ./
        dest: "{{ dest_path }}"
    # Install NodeJS library
    # using multiple shell commands
    - name: Install Nodejs & ExpressJS
      shell: 'curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh'
    # If other package are required mention the package name in "name"
    # eg: ngix, curl, wget, apache2, nodejs
    - name: Install reqired packages
      apt:
        name: nodejs
        state: present
    # npm module installation
    - name: Npm installation
      apt:
        name: npm
        state: present   
    # Install all the necessary Node modules for the project,using `npm`.
      command: npm install
      args:
        chdir: "{{ dest_path }}"
    # Install Forever tool.
    # This tool is used to run the Node server in background
    # and keep tracking of the running process
    - name: npm install pm2@latest -g
      npm: name=pm2 global=yes state=present
    # is already running (avoids restarting the service on each playbook
    # execution)
    - name: Get Forever's list of running processes
      command: pm2 status
      register: pm2_status
      changed_when: false
    # Start the node server using "Foverer"
    # The `when` clause identifies if the server is already
    # running. If so, this task is skipped
    - name: Kill pm2 service
      command: pm2 kill
    - name: Start service
      command: pm2 start npm -- start ./server/app.js --name "{{DOCKER_TAG}}-Service"
      args:
        chdir: "{{ dest_path }}"
