---
- name: Staging server Deployment
  hosts: stageserver
  become_user: root
  become: True
  vars:
    repo_path: nrbaskar/react:{{DOCKER_TAG}}
    dest_path: /home/ec2-user/{{DOCKER_TAG}}

  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present

    - name: Install docker
      yum:
        name: docker
        state: present

    - name: Start the docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present

    - name: Pull docker image
      docker_image:
        name: "{{ repo_path }}"
        tag: "{{ DOCKER_TAG }}"
        source: pull

    - name: Create directory
      file:
        state: directory
        path: "{{ dest_path }}"

    - name: Copy Files
      shell: 'cd "{{ dest_path }}" && aws s3 cp s3://react555-s3bucket/node_sonar_S3bucket .'

  #  - name: Unzip Files
      shell: 'unzip "{{ dest_path }}/node_sonar_S3bucket.zip"'


    - name: Install Node.js & Express.js
      shell: 'curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -'

    - name: Install required packages
      yum:
        name: nodejs
        state: present

    - name: Install Express.js
      command: sudo npm install -g express

    - name: Install React JS package
      command: sudo npm install -g create-react-app

    - name: Install react-dependencies
      command: npm i react-scripts build
      args:
        chdir: "{{ dest_path }}"

    - name: Install necessary Node modules
      command: npm install
      args:
        chdir: "{{ dest_path }}"

    - name: Install Forever tool
      npm:
        name: pm2@latest
        global: yes
        state: present

    - name: Get Forever's list of running processes
      command: pm2 status
      register: pm2_status
      changed_when: false

    - name: Kill pm2 service
      command: pm2 kill

    - name: Start service
      command: pm2 start npm -- start --name "{{ DOCKER_TAG }}-Service"
      args:
        chdir: "{{ dest_path }}"
